### ISSUE TITLE
Repository implementation

### ISSUE THREAD

**Issue by NaskoVasilev** [NikolayIT/ASP.NET-MVC-Template#49]
Is it good idea Delete, Update and Add method in repository to invoke SaveChanges method?

 public virtual Task AddAsync(TEntity entity)
{
    this.DbSet.AddAsync(entity);
    await this.SaveChangesAsync();
}

**Comment by NikolayIT** [comment]
What if you want to add 10000 items and then save the changes? What if you want to do few different operations in one transaction? If we add save changes in repository methods it will limit its usability.
