### ISSUE TITLE
Update the link to the YouTube video in your README.md file

### ISSUE THREAD

**Issue by justEmandleni** [NikolayIT/ASP.NET-MVC-Template#57]
I'm trying to get started.

[This](https://www.youtube.com/watch?v=xhoBt9MscrY) link to the video is not working.  
Did you perhaps change it?

**Comment by NikolayIT** [comment]
1. Download the template as `.zip` file
2. Extract the `ASP.NET Core` folder
3. Run `TemplateRenamer.exe` in the project directory and provide the name of your project
4. Start the solution file with Visual Studio 2019

**Comment by justEmandleni** [comment]
Thanks!
