### ISSUE TITLE
BaseModel inheritance problem

### ISSUE THREAD

**Issue by MarinMarinov** [NikolayIT/ASP.NET-MVC-Template#7]
Problems inheriting BaseModel{Tkey} by ApplicationUser, because of ID type.

Solution at http://telerikacademy.com/Forum/Questions/185649/ASP-NET-MVC-Architecture

**Comment by todorm85** [comment]
Added pull request #8

**Comment by pawelangelow** [comment]
I've finished what MarinMarinov suggests and it looks cleaner his way.

**Comment by todorm85** [comment]
Sorry for that, I was actually referencing another problem related to using IdentityUser via IDbRepository{T}, but it solves Marin`s problem as well as a side effect. So I decided to remove the reference to the pull request to avert any more confusion.
